Categories:
  - VPN & Proxy
License: MIT
AuthorName: Andrey Prokopyuk
AuthorWebSite: https://github.com/andre487
SourceCode: https://github.com/andre487/AndroidMegaProxy
IssueTracker: https://github.com/andre487/AndroidMegaProxy/issues
Changelog: https://github.com/andre487/AndroidMegaProxy/releases
AllowedAPKSigningKeys: 8a014a2a558a75b5f900ee0c33cd50f24b7432734912406699fc08866747f822

RepoType: git
Repo: https://github.com/andre487/AndroidMegaProxy.git

Builds:
  - versionName: 0.0.8
    versionCode: 8001
    commit: d314a250df796643ce9e52c60f9b061318634935
    subdir: app
    ndk: 29.0.14206865
    sudo:
      - apt-get update
      - apt-get install -t trixie-backports -y golang-go
      - apt-get install -y gcc libc-dev make openjdk-21-jdk-headless
      - mkdir -p /home/runner/work/AndroidMegaProxy
      - chown -R vagrant:vagrant /home/runner
    gradle:
      - yes
    srclibs:
      - go@go1.26.3
    binary: https://github.com/andre487/AndroidMegaProxy/releases/download/v%v/mega-proxy-armeabi-v7a.apk
    prebuild:
      - sdkmanager 'platforms;android-26'
      - echo 'megaproxyVersionVariant=armeabi-v7a' >> ../gradle.properties
    build:
      - pushd $$go$$/src
      - ./make.bash
      - popd
      - export GOROOT=$$go$$
      - export GOPATH=$HOME/go
      - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      - rm -rf /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cp -a .. /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cd /home/runner/work/AndroidMegaProxy/AndroidMegaProxy/app
      - MEGAPROXY_ANDROID_ABI=armeabi-v7a ../scripts/build-fdroid-native.sh
      - mkdir -p $OLDPWD/libs
      - cp libs/megaproxy.aar $OLDPWD/libs/

  - versionName: 0.0.8
    versionCode: 8002
    commit: d314a250df796643ce9e52c60f9b061318634935
    subdir: app
    ndk: 29.0.14206865
    sudo:
      - apt-get update
      - apt-get install -t trixie-backports -y golang-go
      - apt-get install -y gcc libc-dev make openjdk-21-jdk-headless
      - mkdir -p /home/runner/work/AndroidMegaProxy
      - chown -R vagrant:vagrant /home/runner
    gradle:
      - yes
    srclibs:
      - go@go1.26.3
    binary: https://github.com/andre487/AndroidMegaProxy/releases/download/v%v/mega-proxy-arm64-v8a.apk
    prebuild:
      - sdkmanager 'platforms;android-26'
      - echo 'megaproxyVersionVariant=arm64-v8a' >> ../gradle.properties
    build:
      - pushd $$go$$/src
      - ./make.bash
      - popd
      - export GOROOT=$$go$$
      - export GOPATH=$HOME/go
      - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      - rm -rf /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cp -a .. /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cd /home/runner/work/AndroidMegaProxy/AndroidMegaProxy/app
      - MEGAPROXY_ANDROID_ABI=arm64-v8a ../scripts/build-fdroid-native.sh
      - mkdir -p $OLDPWD/libs
      - cp libs/megaproxy.aar $OLDPWD/libs/

  - versionName: 0.0.8
    versionCode: 8003
    commit: d314a250df796643ce9e52c60f9b061318634935
    subdir: app
    ndk: 29.0.14206865
    sudo:
      - apt-get update
      - apt-get install -t trixie-backports -y golang-go
      - apt-get install -y gcc libc-dev make openjdk-21-jdk-headless
      - mkdir -p /home/runner/work/AndroidMegaProxy
      - chown -R vagrant:vagrant /home/runner
    gradle:
      - yes
    srclibs:
      - go@go1.26.3
    binary: https://github.com/andre487/AndroidMegaProxy/releases/download/v%v/mega-proxy-x86.apk
    prebuild:
      - sdkmanager 'platforms;android-26'
      - echo 'megaproxyVersionVariant=x86' >> ../gradle.properties
    build:
      - pushd $$go$$/src
      - ./make.bash
      - popd
      - export GOROOT=$$go$$
      - export GOPATH=$HOME/go
      - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      - rm -rf /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cp -a .. /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cd /home/runner/work/AndroidMegaProxy/AndroidMegaProxy/app
      - MEGAPROXY_ANDROID_ABI=x86 ../scripts/build-fdroid-native.sh
      - mkdir -p $OLDPWD/libs
      - cp libs/megaproxy.aar $OLDPWD/libs/

  - versionName: 0.0.8
    versionCode: 8004
    commit: d314a250df796643ce9e52c60f9b061318634935
    subdir: app
    ndk: 29.0.14206865
    sudo:
      - apt-get update
      - apt-get install -t trixie-backports -y golang-go
      - apt-get install -y gcc libc-dev make openjdk-21-jdk-headless
      - mkdir -p /home/runner/work/AndroidMegaProxy
      - chown -R vagrant:vagrant /home/runner
    gradle:
      - yes
    srclibs:
      - go@go1.26.3
    binary: https://github.com/andre487/AndroidMegaProxy/releases/download/v%v/mega-proxy-x86_64.apk
    prebuild:
      - sdkmanager 'platforms;android-26'
      - echo 'megaproxyVersionVariant=x86_64' >> ../gradle.properties
    build:
      - pushd $$go$$/src
      - ./make.bash
      - popd
      - export GOROOT=$$go$$
      - export GOPATH=$HOME/go
      - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      - rm -rf /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cp -a .. /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cd /home/runner/work/AndroidMegaProxy/AndroidMegaProxy/app
      - MEGAPROXY_ANDROID_ABI=x86_64 ../scripts/build-fdroid-native.sh
      - mkdir -p $OLDPWD/libs
      - cp libs/megaproxy.aar $OLDPWD/libs/

VercodeOperation:
  - 1000 * %c + 1
  - 1000 * %c + 2
  - 1000 * %c + 3
  - 1000 * %c + 4

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: app/build.gradle.kts|versionCodeBase = (\d+)|.|versionName = "([^"]+)"
CurrentVersion: 0.0.8
CurrentVersionCode: 8004
