Categories:
  - Connectivity
License: MIT
WebSite: https://github.com/andre487/AndroidMegaProxy
SourceCode: https://github.com/andre487/AndroidMegaProxy
IssueTracker: https://github.com/andre487/AndroidMegaProxy/issues
Changelog: https://github.com/andre487/AndroidMegaProxy/releases
AllowedAPKSigningKeys: 8a014a2a558a75b5f900ee0c33cd50f24b7432734912406699fc08866747f822

RepoType: git
Repo: https://github.com/andre487/AndroidMegaProxy.git

Builds:
  - versionName: 0.0.5
    versionCode: 5
    commit: v0.0.5
    subdir: app
    ndk: 29.0.14206865
    sudo:
      - echo "deb https://deb.debian.org/debian bookworm main" > /etc/apt/sources.list.d/bookworm.list
      - apt-get update
      - apt-get install -t trixie-backports -y golang-go
      - apt-get install -y gcc libc-dev make
      - apt-get install -y -t bookworm openjdk-17-jdk-headless
      - sdkmanager 'platforms;android-26'
      - mkdir -p /home/runner/work/AndroidMegaProxy
      - chown -R vagrant:vagrant /home/runner
    gradle:
      - yes
    srclibs:
      - go@go1.26.3
    binary: https://github.com/andre487/AndroidMegaProxy/releases/download/v%v/mega-proxy-universal.apk
    build:
      - pushd $$go$$/src
      - ./make.bash
      - popd
      - export GOROOT=$$go$$
      - export GOPATH=$HOME/go
      - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      - cp -a .. /home/runner/work/AndroidMegaProxy/AndroidMegaProxy
      - cd /home/runner/work/AndroidMegaProxy/AndroidMegaProxy/app
      - ../scripts/build-fdroid-native.sh
      - cp libs/megaproxy.aar $OLDPWD/libs/

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 0.0.5
CurrentVersionCode: 5
